"""Scenario production helpers for non-authoritative authoring inputs."""

from comp_scenario_packs.generation.apply import (
    SemanticCase,
    SemanticCaseApplyError,
    apply_mutation_card,
)
from comp_scenario_packs.generation.authoring import (
    AuthoringSpec,
    AuthoringSpecError,
    BaseCase,
    Grammar,
    Invariant,
    MutationCard,
    load_authoring_spec,
)
from comp_scenario_packs.generation.evaluate import (
    InvariantEvaluationError,
    SyndromeEvaluation,
    evaluate_semantic_case,
)
from comp_scenario_packs.generation.results import (
    CASE_RESULT_SAMPLING_PLAN_SCHEMA_VERSION,
    CASE_RESULT_SCHEMA_VERSION,
    CASE_RESULT_SELECTION_PLAN_SCHEMA_VERSION,
    CASE_RESULT_SUMMARY_COMPARISON_SCHEMA_VERSION,
    CASE_RESULT_SUMMARY_SCHEMA_VERSION,
    CaseResultContext,
    build_case_result,
    build_case_result_sampling_plan,
    build_case_result_selection_plan,
    compare_case_result_summaries,
    load_case_result_sampling_plan_json,
    load_case_result_summary_comparison_json,
    load_case_result_summary_json,
    stable_hash,
    summarize_case_result_jsonl,
    summarize_case_results,
    syndrome_bucket_key,
    write_case_result_sampling_plan_json,
    write_case_result_selection_plan_json,
    write_case_result_summary_comparison_json,
    write_case_result_summary_json,
    write_case_result_jsonl,
)

__all__ = [
    "AuthoringSpec",
    "AuthoringSpecError",
    "BaseCase",
    "CASE_RESULT_SAMPLING_PLAN_SCHEMA_VERSION",
    "CASE_RESULT_SCHEMA_VERSION",
    "CASE_RESULT_SELECTION_PLAN_SCHEMA_VERSION",
    "CASE_RESULT_SUMMARY_COMPARISON_SCHEMA_VERSION",
    "CASE_RESULT_SUMMARY_SCHEMA_VERSION",
    "CaseResultContext",
    "Grammar",
    "Invariant",
    "InvariantEvaluationError",
    "MutationCard",
    "SemanticCase",
    "SemanticCaseApplyError",
    "SyndromeEvaluation",
    "apply_mutation_card",
    "build_case_result",
    "build_case_result_sampling_plan",
    "build_case_result_selection_plan",
    "compare_case_result_summaries",
    "evaluate_semantic_case",
    "load_case_result_sampling_plan_json",
    "load_case_result_summary_comparison_json",
    "load_case_result_summary_json",
    "load_authoring_spec",
    "stable_hash",
    "summarize_case_result_jsonl",
    "summarize_case_results",
    "syndrome_bucket_key",
    "write_case_result_sampling_plan_json",
    "write_case_result_selection_plan_json",
    "write_case_result_summary_comparison_json",
    "write_case_result_summary_json",
    "write_case_result_jsonl",
]
